my_shop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]   

my_shop/authapp/urls.py
from django.urls import path, re_path
from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    re_path(
        r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', 
        views.verify, name='verify'),
]

my_shop/basketapp/urls.py
from django.urls import path
from . import views

app_name = "basketapp"

urlpatterns = [
    path("", views.view, name="view"),
    path("add/<int:product_id>", views.add, name="add"),
    path("remove/<int:basket_item_id>", views.remove, name="remove"),
]
 

my_shop/mainapp/urls.py
from django.urls import path
from . import views

app_name = "mainapp"

urlpatterns = [
    path("", views.products, name="all"),
    path("<int:category_id>", views.category, name="category"),
    path("<int:category_id>/<int:page>", views.category, name="paged_category"),
    path("product/<int:product_id>", views.product, name="product"),
]

my_shop/my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp



urlpatterns = [
    # path("admin/", admin.site.urls),
    path('', include('social_django.urls', namespace="social")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.index, name='main'),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")), 
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_shop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path

app_name="ordersapp"

urlpatterns = [
path('', ordersapp.OrderList.as_view(), name='orders_list'),
path('forming/complete/(<int:pk>', ordersapp.order_forming_complete, name='order_forming_complete'),
path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
path('read/(<int:pk>', ordersapp.OrderDetail.as_view(), name='order_read'),
path('update/<int:pk>', ordersapp.OrderUpdate.as_view(), name='order_update'),
path('delete/<int:pk>', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

my_shop/mainapp/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=50)
    description = models.TextField(verbose_name="описание", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(verbose_name="имя", max_length=50)
    price = models.DecimalField(
        verbose_name="цена", decimal_places=2, max_digits=7, default=0
    )
    color = models.PositiveIntegerField(verbose_name="цвет", default=0x000000)
    description = models.TextField(verbose_name="описание", blank=True)
    image = models.ImageField(verbose_name="картинка", blank=True, upload_to="products")
    quantity = models.PositiveIntegerField(verbose_name="количество", default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

my_shop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http.request import HttpRequest
from .models import Product
from .models import ProductCategory
import random
from django.core.paginator import Paginator, EmptyPage


def index(request):
    products = Product.objects.all()

    return render(
        request,
        "mainapp/index.html",
        context={
            "title": "Главная",
             
            "products": products
            },
    )


def product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    categories = ProductCategory.objects.all()
    return render(
        request,
        "mainapp/product.html",
        context={
            "title": "Продукты",
            
            "product": product,
            "categories": categories,
            "category": product.category,
        },
    )    


def contact(request):
    return render(
        request,
        "mainapp/contact.html",
        context={
            "title": "Контакты",
            
        },
    )


def get_hot_product(queryset):
    return random.choice(queryset)


def products(request):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    hot_product = get_hot_product(products)
    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Продукты",
            
            "products": products.exclude(pk=hot_product.pk),
            "categories": categories,
            "hot_product": hot_product,
        },
    )


def category(request, category_id, page=1):
    categories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, pk=category_id)
    products = Product.objects.filter(category=category)
    hot_product = get_hot_product(products)
    paginator = Paginator(products.exclude(pk=hot_product.pk), 3)
    try:
        products_page = paginator.page(page)
    except EmptyPage:
        products_page = paginator.page(paginator.num_pages)

    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Продукты",
          
            "paginator": paginator,
            "page": products_page,
            "products": products_page,
            "categories": categories,
            "hot_product": get_hot_product(products),
            "category": category,
            "hot_product": get_hot_product(products),
        },
    )

my_shop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:all' %}" class="active">все</a></li>
        {% for category in categories %}
        <li><a href="{% url 'products:category' category.id %}" class="active">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>

my_shop/mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url "main" %}" class="logo"></a>
<ul class="menu">
    {% for link in menu_links %}
    <li>
        <a href="{% url link.url %}"
            {% if request.resolver_match.url_name == link.url %}
            class="active"
            {% endif %}>
            {{ link.name }}
        </a>
    </li>
    {% endfor %}

{% if user.is_authenticated %}
    <li>
        <div class="dropdown">
            <a class="dropdown-toggle" href="" data-toggle="dropdown">
                {{ user.first_name | default:'Юзер' }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="{% url 'auth:edit' %}">
                        профиль
                    </a>
                </li>
                <li>
                    <a href="{% url 'ordersapp:orders_list' %}">
                        заказы
                    </a>
                </li>
            </ul>
     </div>
    </li>
{% endif %}

{% if user.is_superuser %}
   <li>
       <a href="{% url 'admin:users' %}">админка</a>
   </li>
{% endif %}


    {% if user.is_authenticated %}

    {% endif %} 
    {% if user.is_superuser %}

    {% endif %} 
    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'basket:view' %}">
            корзина
            {{ user.basket.total_cost }} ({{ user.basket.total_quantity }})
        </a>
    </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>


</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

my_shop/mainapp/templates/mainapp/includes/inc_products.html
{% if paginator %}
    {% if page.has_previous %}
       <a href="{% url 'products:paged_category' category.id page.previous_page_number %}"> Сюда </a>
    {% endif %}
        Страница {{ page.number }} из {{ paginator.num_pages }}
    {% if page.has_next %}
        <a href="{% url 'products:paged_category' category.id page.next_page_number %}"> Туда </a>
    {% endif %}
{% endif %}
{% for product in products %}
<div class="block">
    <a href="{% url 'products:product' product.id %}"><img src="/media/{{ product.image }}" alt="">
        <div class="text">
            <img src="/static/mainapp/img/icon-hover.png" alt="img">
            <h4>{{ product.name }}</h4>
            <p>{{ product.description }} </p>
        </div>
    </a>
</div>
{% endfor %}