my_shop/authapp/urls.py
from django.urls import path, re_path
from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    re_path(
        r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', 
        views.verify, name='verify'),
]

my_shop/my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp



urlpatterns = [
    # path("admin/", admin.site.urls),
    path('', include('social_django.urls', namespace="social")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.index, name='main'),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")), 
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_shop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path

app_name="ordersapp"

urlpatterns = [
path('', ordersapp.OrderList.as_view(), name='orders_list'),
path('forming/complete/(<int:pk>', ordersapp.order_forming_complete, name='order_forming_complete'),
path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
path('read/(<int:pk>', ordersapp.OrderDetail.as_view(), name='order_read'),
path('update/<int:pk>', ordersapp.OrderUpdate.as_view(), name='order_update'),
path('delete/<int:pk>', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

my_shop/ordersapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product
from basketapp.models import Basket

# Create your models here.


class Order(models.Model):

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ('-created',)
    
    CREATED = 'CREATED'
    IN_PROCESSING = 'IN_PROCESSING'
    AWAITING_PAYMENT = 'WAITING_PAYMENT'
    PAID = 'PAID'
    READY = 'READY'
    CANCELED = 'CANCELED'
    FINISHED = 'FINISHED'

    ORDER_STATUS_CHOICES = (
        (CREATED, 'Создан'),
        (IN_PROCESSING, 'В обработке'),
        (AWAITING_PAYMENT, 'ОЖИДАЕТ ОПЛАТЫ'),
        (PAID, 'Оплачен'),
        (READY, 'Готов к выдаче'),
        (CANCELED, 'Отменен'),
        (FINISHED, 'Выдан'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name="Статус", choices=ORDER_STATUS_CHOICES, max_length=20, default=CREATED)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    @property
    def items_with_products(self):
        return self.items.select_related('product')

    def __str__(self):
        return f'Заказ {self.id}'

    def get_total_cost(self): 
        return sum(item.cost for item in self.items_with_products)

    def get_total_quantity(self):
        return sum(item.quantity for item in self.items_with_products)

    def delete(self):
        for item in self.items_with_products:
            Basket.objects.create(
                user=self.user, 
                product=item.product, 
                quantity=item.quantity
                )
        self.is_active = False
        self.save()

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    @property
    def cost(self):
        return self.product.price * self.quantity

my_shop/ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

my_shop/ordersapp/views.py
from django.views.generic import CreateView, UpdateView, DetailView, ListView, DeleteView
from .models import Order, OrderItem
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from .forms import OrderForm, OrderItemForm
from basketapp.models import Basket
from django.db import transaction


class OrderList(ListView):
    model = Order
    
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderDetail(DetailView):
    model = Order


class OrderEditMixin:
    def make_formset(self, instance=None):
        OrderFormSet = inlineformset_factory(
        Order, 
        OrderItem, 
        form=OrderItemForm, 
        extra=1
        )
        formset = OrderFormSet(instance=instance)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=instance)
        else:
            if not instance:
                basket_items = self.request.user.basket.all()
                if len(basket_items):
                    OrderFormSet = inlineformset_factory(
                        Order, 
                        OrderItem, 
                        form=OrderItemForm, 
                        extra=len(basket_items)
                        )
                    formset = OrderFormSet()
                    for num, form in enumerate(formset.forms):
                        form.initial['product'] = basket_items[num].product
                        form.initial['quantity'] = basket_items[num].quantity
                    basket_items.delete()

        return formset

    def save_formset(self, form, formset, instance=None):
        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()
        if not self.object.get_total_cost():
            self.object.delete()


class OrderCreate(OrderEditMixin, CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderCreate, self).get_context_data(**kwargs)
        data['orderitems'] = self.make_formset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']     
        self.save_formset(form, orderitems) 
        return super(OrderCreate, self).form_valid(form)



class OrderUpdate(OrderEditMixin, UpdateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderUpdate, self).get_context_data(**kwargs)
        data['orderitems'] = self.make_formset(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']     
        self.save_formset(form, orderitems, instance=self.object) 
        return super(OrderUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')  


def order_forming_complete(request):

    pass

my_shop/ordersapp/templates/ordersapp/includes/inc_order_actions.html
{% if object.status == 'FM' %}
<button class="btn btn-warning btn-round form-control last">
    <a href="{% url 'ordersapp:order_forming_complete' object.pk %}">
        совершить покупку
    </a>
</button>
<button class="btn btn-default btn-round form-control last">
    <a href="{% url 'ordersapp:order_delete' object.pk %}">удалить</a>
</button>
{% endif %}
<button class="btn btn-info btn-round form-control last">
    <a href="{% url 'ordersapp:orders_list' %}">
        к списку заказов
    </a>
</button>
<button class="btn btn-default btn-round form-control last">
    <a href="{% url 'main' %}">на главную</a>
</button>

my_shop/ordersapp/templates/ordersapp/includes/inc_order_summary.html
{% if object %}
    <div class="order-wrapper">
        <div class="order-h3">Order&nbsp;№{{ object.pk }}&nbsp;from&nbsp;{{ object.created|date:"Y-m-d H:i:s" }}</div>
        <div class="order-h5"><b>customer:</b>&nbsp;
            {% if user.first_name %}
                {{ user.first_name }}
                {% if user.last_name %}
                    {{ user.last_name }}
                {% endif %}
            {% else %}
                {{ user.username }}
            {% endif %}
        </div>
        <div class="order-h5"><b>updated:</b>&nbsp;{{ object.updated|date:"Y-m-d H:i:s" }}</div>
        <div class="order-h5"><b>status:</b>&nbsp;{{ object.get_status_display }}</div>
        <div class="order-h5">
            <b>products total quantity:</b>&nbsp;<span class="order_total_quantity">{{ object.get_total_quantity }}</span>
        </div>
        <div class="order-h4">
            <b>total price:</b>&nbsp;<span class="order_total_cost">{{ object.get_total_cost }}</span>$
        </div>
    </div>
{% else %}
    <div class="order-h3">New order</div>
    <hr>
    <div class="order-h5"><b>customer:</b>&nbsp;
        {% if user.first_name %}
            {{ user.first_name }}
            {% if user.last_name %}
                {{ user.last_name }}
            {% endif %}
        {% else %}
            {{ user.username }}
        {% endif %}
    </div>
        <div class="order-h5">
            <b>products total quantity:</b>&nbsp;<span class="order_total_quantity">
        </span>
        </div>
        <div class="order-h5">
            <b>total price:</b>&nbsp;<span class="order_total_cost">
        </span>$
        </div>
{% endif %}