my_shop/authapp/urls.py
from django.urls import path, re_path
from . import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    re_path(
        r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', 
        views.verify, name='verify'),
]

my_shop/my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp



urlpatterns = [
    # path("admin/", admin.site.urls),
    path('', include('social_django.urls', namespace="social")),
    path("admin/", include("adminapp.urls", namespace="admin")),
    path("", mainapp.index, name='main'),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")), 
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_shop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


def get_activation_key_exp_date():
    return now() + timedelta(hours=48)


class ShopUser(AbstractUser):
    age = models.PositiveIntegerField(verbose_name="возраст", blank=True, default=18)
    avatar = models.ImageField(verbose_name="аватарка", blank=True, upload_to="users")
    phone = models.CharField(verbose_name="телефон", max_length=20, blank=True)
    city = models.CharField(verbose_name="город", max_length=20, blank=True)

    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=get_activation_key_exp_date)

    def is_activation_key_expired(self):
        if now() <= self.activation_key_expires:
            return False
        else:
            return True

 
class ShopUserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Мужской'),
        (FEMALE, 'Женский'),
    )

    user = models.OneToOneField(ShopUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE, related_name="profile")
    about = models.TextField(verbose_name="о себе", max_length=512, blank=True)
    gender = models.CharField(verbose_name="выбор пола", choices=GENDER_CHOICES, max_length=1)

@receiver(post_save, sender=ShopUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        ShopUserProfile.objects.create(user=instance)
    else:
        instance.profile.save()
    

my_shop/authapp/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from .models import ShopUser, ShopUserProfile
from django import forms
import random, hashlib
import os


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ("username", "password")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = (
            "username",
            "first_name",
            "password1",
            "password2",
            "email",
            "age",
            "avatar",
            "city",
            "phone",
        )

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    def save(self):
        user = super().save()
        user.is_active = False
        user.activation_key = hashlib.md5(user.email.encode('utf-8') + os.urandom(16)).hexdigest()
        user.save()
        return user


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = (
            "username",
            "first_name",
            "password",
            "email",
            "age",
            "avatar",
            "city",
            "phone",
        )

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            if field_name == 'password':
                field.widget = forms.HiddenInput()


class ShopUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = ShopUserProfile
        fields = ('about', 'gender')

        def __init__(self, *args, **kwargs):
            super(ShopUserProfileEditForm, self).__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'

my_shop/authapp/views.py
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from .forms import (
    ShopUserLoginForm, 
    ShopUserRegisterForm, 
    ShopUserEditForm,
    ShopUserProfileEditForm)
from django.urls import reverse
from django.contrib import auth
from .utils import send_verify_mail
from .models import ShopUser
from django.db import transaction

# Create your views here.


def login(request):
    if request.method == "POST":
        login_form = ShopUserLoginForm(data=request.POST)
        if login_form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(request, username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("main"))
    else:
        login_form = ShopUserLoginForm()

    return render(
        request,
        "authapp/login.html",
        context={
            "title": "Вход",
            "form": login_form,
        },
    )


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main"))


def register(request):
    if request.method == "POST":
        register_form = ShopUserRegisterForm(request.POST, request.FILES)    
        if register_form.is_valid():
            user = register_form.save()
            send_verify_mail(user)
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    return render(
        request,
        "authapp/register.html",
        context={
            "title": "Регистрация",
            "form": register_form,
        },
    )


@transaction.atomic
def edit(request):
    if request.method == "POST":
        edit_form = ShopUserEditForm(request.POST, request.FILES) 
        profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.profile)   
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('main'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(instance=request.user.profile)

    return render(
        request,
        "authapp/edit.html",
        context={
            "title": "Редактирование",
            "form": edit_form,
            "profile_form": profile_form,
        },
    )


def verify(request, email, activation_key):
    user = get_object_or_404(ShopUser, email=email)
    if user.activation_key == activation_key:
        user.is_active = True
        user.save()
        auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return render(request, 'authapp/verification.html')
        

my_shop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'mainapp/fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                {{ title|title}}
            </div>            
            
            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>   

my_shop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}



{% block content %}
    <form method='POST' url="{% url "auth:edit" %}">
        {% csrf_token %}
        {{ form.as_p }}
        {{ profile_form.as_p }}
        <input type='submit' value='edit'>
    </form>

{% endblock %}

my_shop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}



{% block content %}
    <form method='POST' url="{% url "auth:login" %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='login'>
        <a class="button" href="{% url "social:begin" "github" %}">Войти через гитхаб</a>
    </form>

{% endblock %}

my_shop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}



{% block content %}
    <form method='POST' url="{% url "auth:register" %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='register'>
    </form>

{% endblock %}

my_shop/authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

  {% if user %}
    <h3>Поздравляем!</h3>
    <br>
    <h4>Пользователь {{user.username}} подтвержден.</h4>
  {% else %}
    <h3>Верификация не пройдена.</h3>
  {% endif %}
  <br>
  <button class="btn btn-round form-control">
    <a href="{% url 'main' %}" class="">на главную</a>
  </button>

{% endblock %}